alias g 'git'
alias gst 'git status'
alias gp 'git push'
alias gf 'git push --force'
alias gl 'git pull'
alias gpf 'git push --force'
alias gco 'git checkout'
alias gcb 'git checkout -b'
alias gaa 'git add --all'
alias gcmsg 'git commit -m'
alias grhh 'git reset --hard HEAD'
alias grh 'git reset --hard'
alias ggp 'git-push-set-upstream'
alias ggf 'git-push-set-upstream -f'
alias gcp 'git cherry-pick'
